version: "3.9"
services:
  db:
    container_name: db
    build:
      context: ./build/db
      dockerfile: Dockerfile
      target: dev
    # platform: linux/x86_64  ## add this for Apple Silicon
    tty: true
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - ./build/db/init:/docker-entrypoint-initdb.d
      - type: volume
        source: db
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - practice_docker-nuxt-go-ecs_network

  backend:
    container_name: backend
    build:
      context: ./build/backend
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./backend:/backend
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - practice_docker-nuxt-go-ecs_network

  frontend:
    container_name: frontend
    build:
      context: ./build/frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/frontend:cached
      - nuxt_node_modules:/frontend/node_modules
    ports:
      - 3000:3000
      - 24678:24678
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev" ## 初期構築段階ではコメントアウトする
    networks:
      - practice_docker-nuxt-go-ecs_network

volumes:
  db:
    name: db-volume
  nuxt_node_modules:
    name: nuxt-node-modules-volume

networks:
  practice_docker-nuxt-go-ecs_network:
