version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: ./build/backend
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./backend:/backend
    ports:
      - 8080:8080
    networks:
      - practice_docker-nuxt-go-ecs_network

  frontend:
    container_name: frontend
    build:
      context: build/frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/frontend:cached
      - nuxt_node_modules:/frontend/node_modules
    ports:
      - 3000:3000
      - 24678:24678
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm run dev" ## 初期構築段階ではコメントアウトする
    networks:
      - practice_docker-nuxt-go-ecs_network

volumes:
  nuxt_node_modules:
    name: nuxt-node-modules-volume

networks:
  practice_docker-nuxt-go-ecs_network:
